### ISSUE TITLE
Assign me , I want to contribute 

### ISSUE THREAD

**Issue by Romi904** [ThisisGenuine/Publicia#4]
From me

**Comment by ThisisGenuine** [comment]
okay

**Comment by Romi904** [comment]
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
    <img width="100%" height="100%" align="center" alt="Followers" src="https://raw.githubusercontent.com/Sabyasachi-Seal/Sabyasachi-Seal/main/followers.svg">

 <div align=center>
    <a href="https://github.com/Sabyasachi-Seal">
    <img height=50 width=100% src="https://raw.githubusercontent.com/Sabyasachi-Seal/Sabyasachi-Seal/ouput/divider.gif">
    </a>
 </div>

 <h1 align="center"><a href="https://github.com/romi904"><img width=7% height=15% src="https://raw.githubusercontent.com/romi904/romi904/ouput/Hi.gif"/></a> I'm a
    <a href="https://github.com/Sabyasachi-Seal">
    <img align=center width=100% src="https://readme-typing-svg.herokuapp.com?font=Sora&color=%2336BCF7&size=35&center=true&vCenter=true&width=600%&lines=Cloud+Computing+Enthusiast;Cybersecurity+Passionate;Data+Science+Practitioner;AI+%26+ML+Enthusiast;Computer+Science+Undergrad;Tech+Blogger" />
    </a>
 </h1>
 <div align=center>
    <a href="https://github.com/Sabyasachi-Seal" target="_blank">
    <img align="right" alt="Coding" width=45% height=100% src="https://raw.githubusercontent.com/Sabyasachi-Seal/Sabyasachi-Seal/ouput/coder2.gif" /></a>
    <h4>
       🌱 I’m mostly interested in:
       <a href="https://github.com/Sabyasachi-Seal">
       <img align="center" width=50% height=50% src="https://readme-typing-svg.herokuapp.com?font=Manrope&color=%23F78240&center=true&vCenter=true&width=250%&height=50%&lines=Cloud+Computing;CyberSecurity;Data+Science;AI+ML" /></a>
       <br>
       👯 I’m looking to collaborate on:
       <a href="https://github.com/Sabyasachi-Seal">
       <img align="center" width=50% height=50% src="https://readme-typing-svg.herokuapp.com?font=Manrope&color=%23F7BB45&center=true&vCenter=true&width=250%&height=50%&lines=Data+Science;AI+Projects;Web+Apps;Cloud+Deployment;Social+Media+Bots" /></a>
       <br>
       💬 Talk to me all about:
       <a href="https://github.com/Sabyasachi-Seal">
       <img align="center" width=50% height=50% src="https://readme-typing-svg.herokuapp.com?font=Manrope&color=%234AF736&center=true&vCenter=true&width=250%&height=50%&lines=My+Projects;Upcoming+Events;New+Technology;New+Ideas;Anything+Technical" /></a>
    </h4>
 </div>
 <div align=center>
    <a href="https://github.com/Sabyasachi-Seal">
    <img height=50 width=100% src="https://raw.githubusercontent.com/Sabyasachi-Seal/Sabyasachi-Seal/ouput/divider.gif">
    </a>
 </div>
 <div align="right">
    <a href="https://github.com/Sabyasachi-Seal">
       <h2 align="center"><img alt="Script" width=10% src="https://raw.githubusercontent.com/Sabyasachi-Seal/Sabyasachi-Seal/ouput/script.gif"/>&nbsp;&nbsp;<img width=85% alt="Languages and Tools" src="https://raw.githubusercontent.com/Sabyasachi-Seal/Sabyasachi-Seal/ouput/languagesandtools.svg"/></a>
       </h2>
       <a href="https://github.com/Sabyasachi-Seal">
          <img align="left" width=50% alt="Github" src="https://raw.githubusercontent.com/Sabyasachi-Seal/Sabyasachi-Seal/ouput/coder.gif">
          
       </a>
    </a>
    <p>
       <a href="https://azure.microsoft.com/en-in/" target="_blank" rel="noreferrer">
       <img src="https://www.vectorlogo.zone/logos/microsoft_azure/microsoft_azure-icon.svg" alt="azure" width="12.5%" height="12.5%" /> 
       </a>
       <a href="https://cloud.google.com" target="_blank" rel="noreferrer">
       <img src="https://www.vectorlogo.zone/logos/google_cloud/google_cloud-icon.svg" alt="gcp" width="12.5%" height="12.5%" />
       </a>
       <a href="https://www.linux.org/" target="_blank" rel="noreferrer">
       <img src="https://raw.githubusercontent.com/devicons/devicon/master/icons/linux/linux-original.svg" alt="linux" width="12.5%" height="12.5%" />
       </a>
       </a>
    </p>
    <h2></h2>
    <p>
       <a href="https://git-scm.com/" target="_blank" rel="noreferrer">
       <img src="https://www.vectorlogo.zone/logos/git-scm/git-scm-icon.svg" alt="git" width="12.5%" height="12.5%" />
       </a>
       <a href="https://www.w3.org/html/" target="_blank" rel="noreferrer">
       <img src="https://raw.githubusercontent.com/devicons/devicon/master/icons/html5/html5-original-wordmark.svg" alt="html5" width="12.5%" height="12.5%" />
       </a>
       <a href="https://www.w3schools.com/css/" target="_blank" rel="noreferrer">
       <img src="https://raw.githubusercontent.com/devicons/devicon/master/icons/css3/css3-original-wordmark.svg" alt="css3" width="12.5%" height="12.5%" />
       </a>
    </p>
    <h2></h2>
    <p>
       <a href="https://www.python.org" target="_blank" rel="noreferrer">
       <img src="https://raw.githubusercontent.com/devicons/devicon/master/icons/python/python-original.svg" alt="python" width="12.5%" height="12.5%" />
       </a>
       <a href="https://www.java.com" target="_blank" rel="noreferrer">
       <img src="https://raw.githubusercontent.com/devicons/devicon/master/icons/java/java-original.svg" alt="java" width="12.5%" height="12.5%" />
       </a>
       <a href="https://www.w3schools.com/cpp/" target="_blank" rel="noreferrer">
       <img src="https://raw.githubusercontent.com/devicons/devicon/master/icons/cplusplus/cplusplus-original.svg" alt="cplusplus" width="12.5%" height="12.5%" />
       </a>
    </p>
 </div>
 <div align=center>
    <a href="https://github.com/Sabyasachi-Seal">
    <img height=50 width=100% src="https://raw.githubusercontent.com/Sabyasachi-Seal/Sabyasachi-Seal/ouput/divider.gif">
    </a>
 </div>
 <div align="left">
 <a href="https://github.com/Sabyasachi-Seal">
 <img align="right" width=40% alt="Github" src="https://raw.githubusercontent.com/Sabyasachi-Seal/Sabyasachi-Seal/ouput/github.gif">
 </a>
 <br>
 <a href="https://sabyasachi-seal.github.io">
 <img width=45% height=100% src="https://img.shields.io/website?down_color=red&down_message=DOWN&label=My%20Website&logo=Github&style=for-the-badge&up_message=RUNNING&url=https%3A%2F%2Fsabyasachi-seal.github.io" />
 </a>
 <br>
 <a href="https://github.com/Sabyasachi-Seal">
 <img width=45% height=40% src="http://profileviews.azurewebsites.net/"/>
 </a>
 <br>
 <a href="https://www.linkedin.com/in/sabyasachi-seal-4461711bb/">
 <img width=45% height=100% src="https://img.shields.io/badge/-Connect With Me-blue?style=for-the-badge&logo=Linkedin&logoColor=white&link=https://www.linkedin.com/in/sabyasachi-seal-4461711bb/)](https://www.linkedin.com/in/sabyasachi-seal-4461711bb/"/>
 </a>
 <br>
 <a href="https://www.qwiklabs.com/public_profiles/e3e3af1f-e2c8-48b5-ae19-175dee7b6ef5">
 <img width=45% height=100% src="https://img.shields.io/badge/-Google Cloud Badges-ff69b4?style=for-the-badge&logo=googlecloud&logoColor=white&link=https://www.qwiklabs.com/public_profiles/e3e3af1f-e2c8-48b5-ae19-175dee7b6ef5"/>
 </a>
 <br>
 <a href="https://leetcode.com/sabyasachiseal/">
 <img width=45% height=95% src="https://img.shields.io/badge/-LeetCode Profile-yellow?style=for-the-badge&logo=leetcode&logoColor=white&link=https://leetcode.com/sabyasachiseal/"/>
 </a>
 <div align=center>
    <a href="https://github.com/Sabyasachi-Seal">
    <img height=50 width=100% src="https://raw.githubusercontent.com/Sabyasachi-Seal/Sabyasachi-Seal/ouput/divider.gif">
    </a>
 </div>
 <h2 align="center"><a href="https://github.com/Sabyasachi-Seal"><img alt="Star" width=20% src="https://raw.githubusercontent.com/Sabyasachi-Seal/Sabyasachi-Seal/ouput/star.gif"><img width=80% alt="My Stats" src="./img/mystats.svg"/></a></h2>
 <div align="center">
    <a href="https://github.com/Sabyasachi-Seal">
    <img src="https://github-readme-stats.vercel.app/api?username=sabyasachi-seal&show_icons=true&locale=en&langs_count=20&count_private=true&theme=radical&layout=compact&hide_border=false&bg_color=000000&border_color=808080" width=49% height=100%/>
    </a>
    <a href="https://github.com/Sabyasachi-Seal">
    <img src="https://github-readme-streak-stats.herokuapp.com?user=Sabyasachi-Seal&theme=neon-dark&date_format=M%20j%5B%2C%20Y%5D" alt="sabyasachi-seal" width=49% height=100%/>
    <br/>
    </a>
 </div>
 <h2></h2>
 <div align=center>
    <a href="https://github.com/Sabyasachi-Seal">
    <img src="https://github-profile-trophy.vercel.app/?username=sabyasachi-seal&no-bg=true&theme=onedark&no-frame=true&title=Commits,MultiLanguage,PullRequest,Repositories,Followers,Stars&column=6" alt="zumrudu-anka" width=200% height=100%/>
    </a>
 </div>
 <h2></h2>
 
 <div align=center>
    <a href="https://github.com/Sabyasachi-Seal">
    <img alt="Activity Graph" src="https://activity-graph.herokuapp.com/graph?username=Sabyasachi-Seal&theme=redical&hide_border=true" />
    </a>
 </div>
 <h2></h2>
 <div align=center>
    <a href="https://github.com/Sabyasachi-Seal" target="_blank">
    <img align=center width=100% src="https://raw.githubusercontent.com/Sabyasachi-Seal/Sabyasachi-Seal/main/3DGraphs/profile-night-rainbow.svg" />
    </a>
 </div>
 <h2></h2>
 <div align=center>
    <a href="https://github.com/Sabyasachi-Seal">
    <img width=49% src="https://raw.githubusercontent.com/Sabyasachi-Seal/Sabyasachi-Seal/main/achievements.svg" />
    <img width=49% src="https://raw.githubusercontent.com/Sabyasachi-Seal/Sabyasachi-Seal/main/skyline.svg" />
    </a>
 </div>
 <div align=center>
    <a href="https://github.com/Sabyasachi-Seal">
    <img height=50 width=100% src="https://raw.githubusercontent.com/Sabyasachi-Seal/Sabyasachi-Seal/ouput/divider.gif">
    </a>
 </div>
 <div align=center>
    <a href="https://github.com/Sabyasachi-Seal">
    <img align="center" alt="Coding" width=49% height=100% src="https://raw.githubusercontent.com/Sabyasachi-Seal/Sabyasachi-Seal/main/img/connected.gif" />
    </a>
    <a href="https://github.com/Sabyasachi-Seal">
    <img align="center" alt="Coding" width=49% height=100% src="https://raw.githubusercontent.com/Sabyasachi-Seal/Sabyasachi-Seal/main/img/code.gif" />
    </a>
    
 </div>
 <h2></h2>
 <h3 align="center"><a href="https://github.com/Sabyasachi-Seal"><img width=15% alt="Phone" src="https://raw.githubusercontent.com/Sabyasachi-Seal/Sabyasachi-Seal/ouput/phone.gif">&nbsp;<img width=80% alt="Wanna Talk?" src="https://raw.githubusercontent.com/Sabyasachi-Seal/Sabyasachi-Seal/ouput/wannatalk.svg"/></a></h3>
 <div align=center>
    
    <a href="mailto:iam.sabyasachi.seal@gmail.com" target="_blank">
    <img align=center width=100% src="https://readme-typing-svg.herokuapp.com?font=Sora&color=%2336BCF7&center=true&vCenter=true&width=450%&lines=iam.sabyasachi.seal@gmail.com" />
    <img align=center width=100% src="https://readme-typing-svg.herokuapp.com?font=Sora&color=%232CF7E4&center=true&vCenter=true&width=450%&lines=(%2B91)+891-042-7807" />
    </a>
 </div>
 <div align=center>
    <a href="https://github.com/Sabyasachi-Seal">
    <img height=50 width=100% src="https://raw.githubusercontent.com/Sabyasachi-Seal/Sabyasachi-Seal/ouput/divider.gif">
    </a>
 </div>
 <div align=center>            
    <a href="https://github.com/Sabyasachi-Seal">
    <img width=100% height=100% align="center" alt="Coding" src="https://readme-typing-svg.herokuapp.com?font=Sora&color=a6129c&center=true&vCenter=true&width=450%&lines=Watch+a+Snake+eat+my+contributions+!" />
    <img align="center" alt="Snake" width=100% src="https://raw.githubusercontent.com/Sabyasachi-Seal/Sabyasachi-Seal/ouput/github-snake.svg" />
    </a>
 </div>
 
 <div align=center>
    <a href="https://github.com/Sabyasachi-Seal">
    <img height=50 width=100% src="https://raw.githubusercontent.com/Sabyasachi-Seal/Sabyasachi-Seal/ouput/divider.gif">
    </a>
 </div>
 
 <div align=center>            
    <a href="https://github.com/Sabyasachi-Seal">
    <img width=100% height=100% align="center" alt="Coding" src="https://readme-typing-svg.herokuapp.com?font=Sora&color=e3d20c&center=true&vCenter=true&width=450%&lines=Shoutout+to+my+followers+!!!" />
    <img width=100% height=100% align="center" alt="Followers" src="https://raw.githubusercontent.com/Sabyasachi-Seal/Sabyasachi-Seal/main/followers.svg" />
    </a>
 </div>
 <div align=center>
    <a href="https://github.com/Sabyasachi-Seal">
    <img height=50 width=100% src="https://raw.githubusercontent.com/Sabyasachi-Seal/Sabyasachi-Seal/ouput/divider.gif">
    </a>
 </div>
 <div align=center>
    <a href="https://github.com/Sabyasachi-Seal">            
    <img align="center" alt="Coding Habits" width=100% src="https://raw.githubusercontent.com/Sabyasachi-Seal/Sabyasachi-Seal/main/codehabits.svg" />
    </a>
 </div>
 <h2></h2>
 <div align=center>
    <a href="https://github.com/Sabyasachi-Seal">            
    <img align="center" alt="Activity" width=100% src="https://raw.githubusercontent.com/Sabyasachi-Seal/Sabyasachi-Seal/main/activity.svg" />
    </a>
 </div>
 <div align=center>
    <a href="https://github.com/Sabyasachi-Seal">
    <img height=50 width=100% src="https://raw.githubusercontent.com/Sabyasachi-Seal/Sabyasachi-Seal/ouput/divider.gif">
    </a>
 </div>
 <div align=center>   
    <a href="https://sabyasachi-seal.github.io/">
    <img width=100% align="center" alt="Coding" src="https://readme-typing-svg.herokuapp.com?font=Sora&color=e91e63&center=true&vCenter=true&width=350%&lines=Check+out+my+website+!" />        
    <img align="center" alt="Website Stats" width=100% height=50% src="https://raw.githubusercontent.com/Sabyasachi-Seal/Sabyasachi-Seal/main/website.svg" />
    <img align="center" width=95% alt="Website Thumbnail" width=100% height=50% src="https://raw.githubusercontent.com/Sabyasachi-Seal/Sabyasachi-Seal/ouput/thumbnail.png" />
    </a>
 </div>
 <h2></h2>
 <div align=center>
    <a href="https://open.spotify.com/embed/playlist/73JrRdB8AjHDGRP9lNvZam?utm_source=generator&theme=0">
       <img width=100% height=100% align="center" alt="Coding" src="https://readme-typing-svg.herokuapp.com?font=Sora&color=ff5722&center=true&vCenter=true&width=550%&lines=Wanna+listen+to+the+best+playlist+ever?" /> 
       <img align="right" alt="" width=100% src="https://spotify-github-profile.vercel.app/api/view?uid=31rovcoqi44ew75t535jlndsain4&cover_image=true&theme=novatorem&bar_color=53b14f&bar_color_cover=true" />
       
       
       
    </a>
 </div>
 <div align=center>
    <a href="https://github.com/Sabyasachi-Seal">
    <img align="center" alt="Footer" width=100% src="https://raw.githubusercontent.com/Sabyasachi-Seal/Sabyasachi-Seal/ouput/footer.svg"/>
    
 </div>
 
 <div align=center>
    <a href="https://github.com/Sabyasachi-Seal">
    <img height=50 width=100% src="https://raw.githubusercontent.com/Sabyasachi-Seal/Sabyasachi-Seal/ouput/divider.gif">
    </a>
 </div>
 
 
 
</body>
</html>
